// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package modules

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapIoHistogram            = "io_histogram"
	bpfMapStartTimes             = "start_times"
	bpfMapSwitchCounts           = "switch_counts"
	bpfProgHandleBlockRqComplete = "handle_block_rq_complete"
	bpfProgHandleBlockRqIssue    = "handle_block_rq_issue"
	bpfProgHandleSchedSwitch     = "handle_sched_switch"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleBlockRqComplete *ebpf.ProgramSpec `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.ProgramSpec `ebpf:"handle_block_rq_issue"`
	HandleSchedSwitch     *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	IoHistogram  *ebpf.MapSpec `ebpf:"io_histogram"`
	StartTimes   *ebpf.MapSpec `ebpf:"start_times"`
	SwitchCounts *ebpf.MapSpec `ebpf:"switch_counts"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	IoHistogram  *ebpf.Map `ebpf:"io_histogram"`
	StartTimes   *ebpf.Map `ebpf:"start_times"`
	SwitchCounts *ebpf.Map `ebpf:"switch_counts"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.IoHistogram,
		m.StartTimes,
		m.SwitchCounts,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleBlockRqComplete *ebpf.Program `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.Program `ebpf:"handle_block_rq_issue"`
	HandleSchedSwitch     *ebpf.Program `ebpf:"handle_sched_switch"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleBlockRqComplete,
		p.HandleBlockRqIssue,
		p.HandleSchedSwitch,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
