// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package modules

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfIoStats struct {
	_          structs.HostLayout
	ReadBytes  uint64
	WriteBytes uint64
	ReadCount  uint64
	WriteCount uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapProcessIoStats     = "process_io_stats"
	bpfMapRunqHistogram      = "runq_histogram"
	bpfMapSchedTimes         = "sched_times"
	bpfMapSwitchCounts       = "switch_counts"
	bpfProgHandleSchedSwitch = "handle_sched_switch"
	bpfProgHandleSchedWakeup = "handle_sched_wakeup"
	bpfProgVfsReadRet        = "vfs_read_ret"
	bpfProgVfsWriteRet       = "vfs_write_ret"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
	VfsReadRet        *ebpf.ProgramSpec `ebpf:"vfs_read_ret"`
	VfsWriteRet       *ebpf.ProgramSpec `ebpf:"vfs_write_ret"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ProcessIoStats *ebpf.MapSpec `ebpf:"process_io_stats"`
	RunqHistogram  *ebpf.MapSpec `ebpf:"runq_histogram"`
	SchedTimes     *ebpf.MapSpec `ebpf:"sched_times"`
	SwitchCounts   *ebpf.MapSpec `ebpf:"switch_counts"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ProcessIoStats *ebpf.Map `ebpf:"process_io_stats"`
	RunqHistogram  *ebpf.Map `ebpf:"runq_histogram"`
	SchedTimes     *ebpf.Map `ebpf:"sched_times"`
	SwitchCounts   *ebpf.Map `ebpf:"switch_counts"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ProcessIoStats,
		m.RunqHistogram,
		m.SchedTimes,
		m.SwitchCounts,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup *ebpf.Program `ebpf:"handle_sched_wakeup"`
	VfsReadRet        *ebpf.Program `ebpf:"vfs_read_ret"`
	VfsWriteRet       *ebpf.Program `ebpf:"vfs_write_ret"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
		p.VfsReadRet,
		p.VfsWriteRet,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
